version: '3.8'

services:
  web:
    container_name: venue_event-web-service
    restart: always
    build: .
    ports:
      - "3000:3030"
    environment:
      WAIT_HOST: postgres:5430
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5430:5433"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=shuffle
      - POSTGRES_DB=shuffle
