version: '3.8'

services:
  web:
    container_name: venue_event-web-service
    restart: always
    build: .
    ports: 
      - 8000:3000
    depends_on: 
      - postgres
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - 5445:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    ports: 
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    restart: unless-stopped
    
